### ISSUE TITLE
PlayingCardsExtension instance has no attribute 'arg_parser'

### ISSUE THREAD

**Issue by nleguillarme** [DerElam/inkscape-extension-playing-cards#2]
The GUI is empty (except for the Fold Line tab), and when clicking on Apply, I get the error

Traceback (most recent call last):
  File "PlayingCards.py", line 868, in <module>
    main()
  File "PlayingCards.py", line 863, in main
    extension = PlayingCardsExtension()
  File "PlayingCards.py", line 363, in __init__
    self.init_arg_parser()
  File "PlayingCards.py", line 372, in init_arg_parser
    self.arg_parser.add_argument("--pageName", type=str)
AttributeError: PlayingCardsExtension instance has no attribute 'arg_parser'

**Comment by DerElam** [comment]
What is your OS? What's the version number of Inkscape and the version number of the extension?

**Comment by square-bear** [comment]
I'm having the same issue. My OS is Windows 10 and my extension version number is 1.3.1-2

**Comment by DerElam** [comment]
I was able to reproduce the error using Inkscape 0.92.5 and the extension version 1.3.1. 

The older versions of the extension (up until v1.2.1) were made for Inkscape 0.92 and are incompatible with Inkscape 1.0/1.1. The newer extension versions (v1.3.0 and later) were made for Inkscape 1.0/1.1 and are incompatible with Inkscape 0.92.

Can you confirm that your issue is caused by a version mismatch?

**Comment by nleguillarme** [comment]
Hi, I confirm this version mismatch : my Inkscape version was 0.92, I upgraded to Inkscape 1.1.1
Thank you for your help.
